TMP_DIR := _tmp

define COMMON_LOGIC

PROJECT_NAME := $(1)
$(eval DOC_FILE := $(1).tex)
REPO_ROOT_DIR := $(2)

all: $(PROJECT_NAME)

$(PROJECT_NAME): $(DOC_FILE)
	mkdir -p $(TMP_DIR)
	TEXINPUTS=$(REPO_ROOT_DIR): pdflatex -output-directory=$(TMP_DIR) '\def\reporoot{$(REPO_ROOT_DIR)} \input{$(DOC_FILE)}'
	mv $(TMP_DIR)/$(DOC_FILE:.tex=.pdf) .

clean:
	rm -rf $(TMP_DIR)

cleanall: clean
	rm -f $(DOC_FILE:.tex=.pdf)

.PHONY: all clean
endef

export COMMON_LOGIC
